# Generated by Django 5.0.6 on 2024-08-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('sales', 'Salesperson'), ('accountant', 'Accountant'), ('owner', 'Owner')], max_length=50),
        ),
    ]
