# Generated by Django 5.0.6 on 2024-08-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_saleitem_sale'),
        ('inventory', '0008_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
