# Generated by Django 5.0.6 on 2024-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_saleitem_product_alter_saleitem_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
