# Generated by Django 5.0.6 on 2024-08-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_cogs"),
        ("inventory", "0012_alter_logs_quantity_alter_logs_total_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cogs",
            name="production",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.production",
            ),
        ),
    ]
