# Generated by Django 5.0.6 on 2024-08-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_sale_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_notification', models.BooleanField(default=True)),
            ],
        ),
    ]
