# Generated by Django 4.2.16 on 2024-12-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_saleitem_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='dish',
        ),
    ]
