# Generated by Django 5.0.6 on 2024-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_sale_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
