# Generated by Django 5.0.6 on 2024-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_expense_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
