# Generated by Django 5.0.6 on 2024-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_cashbook_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='credit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='debit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
