# Generated by Django 5.0.6 on 2024-08-07 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_cashbook_credit_alter_cashbook_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
