# Generated by Django 4.2.16 on 2024-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_saleitem_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='void',
            field=models.BooleanField(default=False),
        ),
    ]
