# Generated by Django 4.2.16 on 2024-12-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_sale_void'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='void',
        ),
    ]
