# Generated by Django 4.2.16 on 2024-12-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_sale_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='voi',
            field=models.BooleanField(default=False),
        ),
    ]
