# Generated by Django 4.2.16 on 2025-01-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_cashierexpense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sub_total",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
