# Generated by Django 4.2.16 on 2025-01-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_alter_sale_sub_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashup",
            name="change",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cashup",
            name="void_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cashup",
            name="cashed_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
