# Generated by Django 4.2.16 on 2025-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_cashup_change_cashup_void_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashup",
            name="expenses",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
