# Generated by Django 4.2.16 on 2025-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_cashup_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashup",
            name="difference",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
