# Generated by Django 4.2.16 on 2025-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_cashup_difference"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashup",
            name="cashed",
            field=models.BooleanField(default=True),
        ),
    ]
