# Generated by Django 4.2.16 on 2025-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_cashup_cashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashup",
            name="cashed",
            field=models.BooleanField(default=False),
        ),
    ]
