# Generated by Django 4.2.16 on 2024-12-07 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('finance', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dish'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.production'),
        ),
        migrations.AddField(
            model_name='productioninventory',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.expense'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.production'),
        ),
        migrations.AddField(
            model_name='minorrawmaterials',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='minorproductionitems',
            name='minor_raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='minorproductionitems',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.production'),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.mealcategory'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish',
            field=models.ManyToManyField(related_name='dishes', to='inventory.dish'),
        ),
        migrations.AddField(
            model_name='logs',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='logs',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='logs',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.sale'),
        ),
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.dish'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='endofdayitems',
            name='end_of_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.endofday'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='allocatedrawmaterials',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.production'),
        ),
        migrations.AddField(
            model_name='allocatedrawmaterials',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
