# Generated by Django 5.0.6 on 2024-08-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='portions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
