# Generated by Django 5.0.6 on 2024-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='time_created',
            field=models.TimeField(),
        ),
    ]
