# Generated by Django 5.0.6 on 2024-08-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_production_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='production',
            name='time_created',
        ),
    ]
