# Generated by Django 5.0.6 on 2024-08-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productionitems_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dish',
            field=models.ManyToManyField(related_name='dishes', to='inventory.dish'),
        ),
        migrations.DeleteModel(
            name='MealDish',
        ),
    ]
