# Generated by Django 5.0.6 on 2024-08-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="minor_raw_material",
            new_name="raw_material",
        ),
        migrations.RenameField(
            model_name="productionitems",
            old_name="lf_carried_forward_quantity",
            new_name="lf_brought_forward_quantity",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="major_raw_material",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="dish",
        ),
        migrations.RemoveField(
            model_name="productionitems",
            name="production_completion_time",
        ),
        migrations.RemoveField(
            model_name="productionitems",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="productionitems",
            name="raw_material",
        ),
        migrations.RemoveField(
            model_name="productionitems",
            name="rm_carried_forward_quantity",
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredient",
            field=models.ManyToManyField(to="inventory.ingredient"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="portion_multiplier",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProductionInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
    ]
