# Generated by Django 4.2.16 on 2024-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="dish",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="meal",
            field=models.BooleanField(default=True),
        ),
    ]
