# Generated by Django 5.0.6 on 2024-08-02 09:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rawmaterials_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='raw_material',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='handling_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='other_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 11, 16, 3, 283064)),
        ),
        migrations.RenameModel(
            old_name='FinishedGoodsCategory',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portion_multiplier', models.FloatField(blank=True, default=1, null=True)),
                ('description', models.TextField()),
                ('deactivate', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement')),
            ],
        ),
        migrations.AddField(
            model_name='logs',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='RawMaterials',
        ),
        migrations.DeleteModel(
            name='FinishedProduct',
        ),
    ]
