# Generated by Django 5.0.6 on 2024-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_meal_dish_delete_mealdish'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
