# Generated by Django 5.0.6 on 2024-08-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0003_rename_minor_raw_material_ingredient_raw_material_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.dish",
            ),
        ),
    ]
