# Generated by Django 5.0.6 on 2024-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_meal_deactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='portions_sold',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
