# Generated by Django 5.0.6 on 2024-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_production_date_created_production_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='raw_material',
            new_name='major_raw_material',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='raw_material',
            new_name='minor_raw_material',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
