# Generated by Django 5.0.6 on 2024-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_dish_ingredient_ingredient_dish"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionitems",
            name="quantity_kgs",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
