# Generated by Django 5.0.6 on 2024-08-02 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='name',
            new_name='unit_name',
        ),
        migrations.AddField(
            model_name='product',
            name='finished_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_material',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 13, 52, 9, 80481)),
        ),
    ]
