# Generated by Django 5.0.6 on 2024-08-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_raw_material_dish_major_raw_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='major_raw_material',
        ),
        migrations.AddField(
            model_name='dish',
            name='major_raw_material',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
