# Generated by Django 4.2.16 on 2025-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_budget_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitem",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
