# Generated by Django 5.0.6 on 2024-08-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_productionitems_quantity_kgs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionitems",
            name="quantity_kgs",
        ),
        migrations.AlterField(
            model_name="productionitems",
            name="actual_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productionitems",
            name="lf_brought_forward_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
