# Generated by Django 5.0.6 on 2024-08-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_dish_major_raw_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='major_raw_material',
        ),
        migrations.AddField(
            model_name='dish',
            name='major_raw_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
    ]
