# Generated by Django 5.0.6 on 2024-08-02 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_min_stock_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('exempted', 'Exempted'), ('standard', 'Standard'), ('zero rated', 'Zero Rated')], default='standard', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 14, 8, 59, 318943)),
        ),
    ]
