# Generated by Django 5.0.6 on 2024-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_allocatedrawmaterials"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocatedrawmaterials",
            name="remaining_quantity",
            field=models.FloatField(null=True),
        ),
    ]
