# Generated by Django 5.0.6 on 2024-08-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productionrawmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='declared_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='staff_portions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
