# Generated by Django 5.0.6 on 2024-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_allocatedrawmaterials_remaining_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
