# Generated by Django 5.0.6 on 2024-08-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_purchaseorderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
