# Generated by Django 5.0.6 on 2024-08-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_productionitems_declared_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinorProductionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity_per_kg', models.FloatField()),
                ('planned_quantity', models.FloatField()),
                ('expected_quantity', models.FloatField()),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('minor_raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='minor_raw_material_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.minorproductionitems'),
        ),
    ]
