# Generated by Django 5.0.6 on 2024-08-02 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_price_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact',
            new_name='contact_name',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 15, 21, 14, 962483)),
        ),
    ]
