# Generated by Django 5.0.6 on 2024-08-02 14:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_contact_supplier_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 16, 15, 23, 182596)),
        ),
    ]
