# Generated by Django 5.0.6 on 2024-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionrawmaterials",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
