# Generated by Django 5.0.6 on 2024-08-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_minorproductionitems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='minor_raw_material_plan',
        ),
        migrations.AddField(
            model_name='minorproductionitems',
            name='production',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='inventory.production'),
            preserve_default=False,
        ),
    ]
