# Generated by Django 5.0.6 on 2024-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_productionrawmaterials_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="logs",
            name="total_quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_stock_level",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productionitems",
            name="declared_quantity",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productionitems",
            name="portions",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productionitems",
            name="portions_sold",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productionitems",
            name="staff_portions",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="received_quantity",
            field=models.FloatField(default=0),
        ),
    ]
