# Generated by Django 5.0.6 on 2024-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_production_minor_raw_material_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
