# Generated by Django 5.0.6 on 2024-08-03 08:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='left_overs',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='sold_quantity',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='variance',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='wastage',
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='raw_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 10, 43, 40, 48721)),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='dish',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.dish'),
            preserve_default=False,
        ),
    ]
