# Generated by Django 5.0.6 on 2024-08-03 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_dish_remove_productionitems_left_overs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 11, 0, 30, 918083)),
        ),
    ]
