# Generated by Django 5.0.6 on 2024-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_reorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="reorder",
            name="approx_days",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reorder",
            name="reorder_quantity",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
