# Generated by Django 5.0.6 on 2024-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_end_of_day_end_of_time_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_of_time_items',
            name='expected',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
