# Generated by Django 5.0.6 on 2024-08-03 09:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='production_plan_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='production',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.production'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 11, 8, 19, 37421)),
        ),
    ]
