# Generated by Django 5.0.6 on 2024-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_end_of_day_endofday_endofdayitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofday',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
