# Generated by Django 5.0.6 on 2024-08-03 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_meal_dish_raw_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionplaninline',
            old_name='declared_quantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 15, 9, 39, 19424)),
        ),
    ]
