# Generated by Django 5.0.6 on 2024-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_endofday_cashed_amount_endofday_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofday',
            name='cashed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='endofday',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
