# Generated by Django 5.0.6 on 2024-08-04 15:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_declared_quantity_productionplaninline_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplaninline',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.dish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 17, 34, 48, 723843)),
        ),
    ]
