# Generated by Django 5.0.6 on 2024-08-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_minorrawmaterials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minorrawmaterials',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
