# Generated by Django 5.0.6 on 2024-08-04 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_productionplaninline_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='production_completion_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 14, 41, 20, 229995)),
        ),
    ]
