# Generated by Django 5.0.6 on 2024-08-04 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_productionitems_production_completion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='actual_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionitems',
            name='lf_carried_forward_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionitems',
            name='rm_carried_forward_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionplaninline',
            name='production_completion_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 14, 47, 46, 132730)),
        ),
    ]
