# Generated by Django 5.0.6 on 2024-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_quanity_minorrawmaterials_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorproductionitems',
            name='actual_quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
