# Generated by Django 5.0.6 on 2024-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_minorproductionitems_actual_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorproductionitems',
            name='actual_quantity',
            field=models.FloatField(null=True),
        ),
    ]
