# Generated by Django 5.0.6 on 2024-08-04 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_productionitems_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 16, 18, 29, 140983)),
        ),
        migrations.DeleteModel(
            name='ProductionPlanInline',
        ),
    ]
