# Generated by Django 5.0.6 on 2024-08-05 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_productionitems_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='remaining_raw_material',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 38, 25, 655489)),
        ),
    ]
