# Generated by Django 5.0.6 on 2024-08-05 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_productionitems_remaining_raw_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 49, 14, 337225)),
        ),
    ]
