# Generated by Django 5.0.6 on 2024-08-05 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_production_declared_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 14, 10, 14, 977638)),
        ),
    ]
