# Generated by Django 5.0.6 on 2024-08-05 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_productionitems_declared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='left_overs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='wastage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 16, 35, 28, 975561)),
        ),
    ]
