# Generated by Django 5.0.6 on 2024-08-05 14:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_productionitems_left_overs_productionitems_wastage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 16, 47, 11, 507133)),
        ),
    ]
