# Generated by Django 5.0.6 on 2024-08-05 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_production_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitems',
            name='actual_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='left_overs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='lf_carried_forward_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='remaining_raw_material',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='rm_carried_forward_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='wastage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 18, 33, 38, 502554)),
        ),
    ]
