# Generated by Django 5.0.6 on 2024-08-06 13:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_productionitems_actual_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaredrawmaterial',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='declaredwastagemeal',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='saleportion',
            name='meal',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 15, 6, 4, 874955)),
        ),
        migrations.CreateModel(
            name='MealDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dish')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.meal')),
            ],
        ),
        migrations.DeleteModel(
            name='DeclaredLeftOverDish',
        ),
        migrations.DeleteModel(
            name='DeclaredRawMaterial',
        ),
        migrations.DeleteModel(
            name='DeclaredWastageMeal',
        ),
        migrations.DeleteModel(
            name='SalePortion',
        ),
    ]
