# Generated by Django 5.0.6 on 2024-08-06 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_declaredrawmaterial_raw_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 15, 12, 38, 602261)),
        ),
    ]
