# Generated by Django 5.0.6 on 2024-08-06 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_meal_price_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 16, 42, 19, 97097)),
        ),
    ]
